import { PrismaClient, UserRole, TelephonyProvider } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // ============================================
  // 1. Create admin user
  // ============================================
  const adminPassword = await bcrypt.hash('admin123456', 12);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@signalhunt.com' },
    update: {},
    create: {
      email: 'admin@signalhunt.com',
      passwordHash: adminPassword,
      fullName: 'Admin User',
      role: UserRole.ADMIN,
    },
  });
  console.log(`  ✅ Admin user: ${admin.email}`);

  // ============================================
  // 2. Create test BDR users
  // ============================================
  const bdrPassword = await bcrypt.hash('bdr123456', 12);

  const bdr1 = await prisma.user.upsert({
    where: { email: 'bdr1@signalhunt.com' },
    update: {},
    create: {
      email: 'bdr1@signalhunt.com',
      passwordHash: bdrPassword,
      fullName: 'Alex Johnson',
      role: UserRole.BDR,
    },
  });
  console.log(`  ✅ BDR user: ${bdr1.email}`);

  const bdr2 = await prisma.user.upsert({
    where: { email: 'bdr2@signalhunt.com' },
    update: {},
    create: {
      email: 'bdr2@signalhunt.com',
      passwordHash: bdrPassword,
      fullName: 'Sarah Williams',
      role: UserRole.BDR,
    },
  });
  console.log(`  ✅ BDR user: ${bdr2.email}`);

  // ============================================
  // 3. Create test phone numbers
  // ============================================
  const phone1 = await prisma.phoneNumber.upsert({
    where: {
      number_provider: {
        number: '+441234567890',
        provider: TelephonyProvider.TWILIO,
      },
    },
    update: { assignedUserId: bdr1.id },
    create: {
      number: '+441234567890',
      countryCode: 'GB',
      provider: TelephonyProvider.TWILIO,
      providerSid: 'PN_TEST_1',
      assignedUserId: bdr1.id,
    },
  });
  console.log(`  ✅ Phone number: ${phone1.number} → ${bdr1.fullName}`);

  const phone2 = await prisma.phoneNumber.upsert({
    where: {
      number_provider: {
        number: '+491234567890',
        provider: TelephonyProvider.TWILIO,
      },
    },
    update: { assignedUserId: bdr2.id },
    create: {
      number: '+491234567890',
      countryCode: 'DE',
      provider: TelephonyProvider.TWILIO,
      providerSid: 'PN_TEST_2',
      assignedUserId: bdr2.id,
    },
  });
  console.log(`  ✅ Phone number: ${phone2.number} → ${bdr2.fullName}`);

  // ============================================
  // 4. Create test leads (34 total)
  // ============================================
  const testLeads = [
    {
      companyName: 'TechStart GmbH',
      contactName: 'Max Mueller',
      contactTitle: 'CTO',
      phoneNumber: '+4915123456789',
      country: 'DE',
      location: 'Berlin',
      headcount: 45,
      industry: 'Software Development',
      email: 'max.mueller@techstart.de',
      website: 'https://techstart.de',
      personalLinkedin: 'https://linkedin.com/in/maxmueller',
      companyLinkedin: 'https://linkedin.com/company/techstart-gmbh',
      companyOverview: 'B2B SaaS company building developer tools for enterprise teams.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'CloudScale Ltd',
      contactName: 'James Smith',
      contactTitle: 'VP Engineering',
      phoneNumber: '+447911123456',
      country: 'GB',
      location: 'London',
      headcount: 120,
      industry: 'Cloud Computing',
      email: 'james.smith@cloudscale.co.uk',
      website: 'https://cloudscale.co.uk',
      personalLinkedin: 'https://linkedin.com/in/jamessmith',
      companyLinkedin: 'https://linkedin.com/company/cloudscale-ltd',
      companyOverview: 'Cloud infrastructure provider specializing in auto-scaling solutions.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'DataFlow BV',
      contactName: 'Jan de Vries',
      contactTitle: 'Head of Sales',
      phoneNumber: '+31612345678',
      country: 'NL',
      location: 'Amsterdam',
      headcount: 80,
      industry: 'Data Analytics',
      email: 'jan.devries@dataflow.nl',
      website: 'https://dataflow.nl',
      personalLinkedin: 'https://linkedin.com/in/jandevries',
      companyLinkedin: 'https://linkedin.com/company/dataflow-bv',
      companyOverview: 'Data pipeline automation company serving mid-market enterprises.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'InnovateTech SA',
      contactName: 'Pierre Dubois',
      contactTitle: 'CEO',
      phoneNumber: '+33612345678',
      country: 'FR',
      location: 'Paris',
      headcount: 200,
      industry: 'Artificial Intelligence',
      email: 'pierre.dubois@innovatetech.fr',
      website: 'https://innovatetech.fr',
      personalLinkedin: 'https://linkedin.com/in/pierredubois',
      companyLinkedin: 'https://linkedin.com/company/innovatetech-sa',
      companyOverview: 'AI-powered business intelligence platform for retail industry.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'NordSecure AB',
      contactName: 'Erik Lindgren',
      contactTitle: 'CISO',
      phoneNumber: '+46701234567',
      country: 'SE',
      location: 'Stockholm',
      headcount: 95,
      industry: 'Cybersecurity',
      email: 'erik.lindgren@nordsecure.se',
      website: 'https://nordsecure.se',
      personalLinkedin: 'https://linkedin.com/in/eriklindgren',
      companyLinkedin: 'https://linkedin.com/company/nordsecure',
      companyOverview: 'Endpoint security platform for Nordic enterprise customers.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'FinEdge GmbH',
      contactName: 'Anna Becker',
      contactTitle: 'VP Product',
      phoneNumber: '+4917612345678',
      country: 'DE',
      location: 'Frankfurt',
      headcount: 150,
      industry: 'FinTech',
      email: 'anna.becker@finedge.de',
      website: 'https://finedge.de',
      personalLinkedin: 'https://linkedin.com/in/annabecker',
      companyLinkedin: 'https://linkedin.com/company/finedge-gmbh',
      companyOverview: 'Open banking APIs for mid-size European banks.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'HealthBridge Ltd',
      contactName: 'Olivia Brown',
      contactTitle: 'COO',
      phoneNumber: '+447700123456',
      country: 'GB',
      location: 'Manchester',
      headcount: 60,
      industry: 'HealthTech',
      email: 'olivia.brown@healthbridge.co.uk',
      website: 'https://healthbridge.co.uk',
      personalLinkedin: 'https://linkedin.com/in/oliviabrown',
      companyLinkedin: 'https://linkedin.com/company/healthbridge-ltd',
      companyOverview: 'NHS-integrated patient management and telemedicine platform.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'LogiTrack SpA',
      contactName: 'Marco Rossi',
      contactTitle: 'Director of Operations',
      phoneNumber: '+393481234567',
      country: 'IT',
      location: 'Milan',
      headcount: 110,
      industry: 'Logistics',
      email: 'marco.rossi@logitrack.it',
      website: 'https://logitrack.it',
      personalLinkedin: 'https://linkedin.com/in/marcorossi',
      companyLinkedin: 'https://linkedin.com/company/logitrack-spa',
      companyOverview: 'Real-time fleet tracking and last-mile delivery optimization.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'GreenWatt AS',
      contactName: 'Sven Olsen',
      contactTitle: 'Head of Business Development',
      phoneNumber: '+4790123456',
      country: 'NO',
      location: 'Oslo',
      headcount: 35,
      industry: 'CleanTech',
      email: 'sven.olsen@greenwatt.no',
      website: 'https://greenwatt.no',
      personalLinkedin: 'https://linkedin.com/in/svenolsen',
      companyLinkedin: 'https://linkedin.com/company/greenwatt-as',
      companyOverview: 'Smart grid energy management for commercial buildings.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'PropVault AG',
      contactName: 'Lukas Weber',
      contactTitle: 'CEO',
      phoneNumber: '+41791234567',
      country: 'CH',
      location: 'Zurich',
      headcount: 25,
      industry: 'PropTech',
      email: 'lukas.weber@propvault.ch',
      website: 'https://propvault.ch',
      personalLinkedin: 'https://linkedin.com/in/lukasweber',
      companyLinkedin: 'https://linkedin.com/company/propvault-ag',
      companyOverview: 'Digital property management for Swiss and German real estate firms.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'Edulabs BV',
      contactName: 'Sophie van den Berg',
      contactTitle: 'CTO',
      phoneNumber: '+31620123456',
      country: 'NL',
      location: 'Rotterdam',
      headcount: 40,
      industry: 'EdTech',
      email: 'sophie.vdberg@edulabs.nl',
      website: 'https://edulabs.nl',
      personalLinkedin: 'https://linkedin.com/in/sophievdberg',
      companyLinkedin: 'https://linkedin.com/company/edulabs-bv',
      companyOverview: 'AI-powered adaptive learning platform for K-12 schools.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'RetailPulse SL',
      contactName: 'Carlos Garcia',
      contactTitle: 'VP Sales EMEA',
      phoneNumber: '+34612345678',
      country: 'ES',
      location: 'Barcelona',
      headcount: 180,
      industry: 'Retail Technology',
      email: 'carlos.garcia@retailpulse.es',
      website: 'https://retailpulse.es',
      personalLinkedin: 'https://linkedin.com/in/carlosgarcia',
      companyLinkedin: 'https://linkedin.com/company/retailpulse-sl',
      companyOverview: 'In-store analytics and customer behavior tracking for retail chains.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'AeroLink GmbH',
      contactName: 'Thomas Schmidt',
      contactTitle: 'Head of Engineering',
      phoneNumber: '+4915198765432',
      country: 'DE',
      location: 'Munich',
      headcount: 70,
      industry: 'Aerospace',
      email: 'thomas.schmidt@aerolink.de',
      website: 'https://aerolink.de',
      personalLinkedin: 'https://linkedin.com/in/thomasschmidt',
      companyLinkedin: 'https://linkedin.com/company/aerolink-gmbh',
      companyOverview: 'Drone fleet management software for agricultural and industrial use.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'BioTrace Ltd',
      contactName: 'Emily Watson',
      contactTitle: 'Research Director',
      phoneNumber: '+447855123456',
      country: 'GB',
      location: 'Cambridge',
      headcount: 30,
      industry: 'Biotechnology',
      email: 'emily.watson@biotrace.co.uk',
      website: 'https://biotrace.co.uk',
      personalLinkedin: 'https://linkedin.com/in/emilywatson',
      companyLinkedin: 'https://linkedin.com/company/biotrace-ltd',
      companyOverview: 'Rapid diagnostic testing kits for infectious diseases.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'PayStream SA',
      contactName: 'Marie Laurent',
      contactTitle: 'CFO',
      phoneNumber: '+33672345678',
      country: 'FR',
      location: 'Lyon',
      headcount: 90,
      industry: 'Payments',
      email: 'marie.laurent@paystream.fr',
      website: 'https://paystream.fr',
      personalLinkedin: 'https://linkedin.com/in/marielaurent',
      companyLinkedin: 'https://linkedin.com/company/paystream-sa',
      companyOverview: 'Cross-border B2B payment processing for European SMEs.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'MediConnect Oy',
      contactName: 'Mikko Virtanen',
      contactTitle: 'CEO',
      phoneNumber: '+358401234567',
      country: 'FI',
      location: 'Helsinki',
      headcount: 55,
      industry: 'HealthTech',
      email: 'mikko.virtanen@mediconnect.fi',
      website: 'https://mediconnect.fi',
      personalLinkedin: 'https://linkedin.com/in/mikkovirtanen',
      companyLinkedin: 'https://linkedin.com/company/mediconnect-oy',
      companyOverview: 'Electronic health records interoperability platform for hospitals.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'BuildSmart Sp. z o.o.',
      contactName: 'Pawel Kowalski',
      contactTitle: 'CTO',
      phoneNumber: '+48512345678',
      country: 'PL',
      location: 'Warsaw',
      headcount: 130,
      industry: 'Construction Tech',
      email: 'pawel.kowalski@buildsmart.pl',
      website: 'https://buildsmart.pl',
      personalLinkedin: 'https://linkedin.com/in/pawelkowalski',
      companyLinkedin: 'https://linkedin.com/company/buildsmart-pl',
      companyOverview: 'BIM collaboration and project management for construction firms.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'FoodChain NV',
      contactName: 'Thomas De Smet',
      contactTitle: 'Head of Product',
      phoneNumber: '+32471234567',
      country: 'BE',
      location: 'Brussels',
      headcount: 45,
      industry: 'FoodTech',
      email: 'thomas.desmet@foodchain.be',
      website: 'https://foodchain.be',
      personalLinkedin: 'https://linkedin.com/in/thomasdesmet',
      companyLinkedin: 'https://linkedin.com/company/foodchain-nv',
      companyOverview: 'Supply chain traceability for organic food producers.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'TravelMate ApS',
      contactName: 'Lars Hansen',
      contactTitle: 'VP Marketing',
      phoneNumber: '+4520123456',
      country: 'DK',
      location: 'Copenhagen',
      headcount: 65,
      industry: 'Travel Tech',
      email: 'lars.hansen@travelmate.dk',
      website: 'https://travelmate.dk',
      personalLinkedin: 'https://linkedin.com/in/larshansen',
      companyLinkedin: 'https://linkedin.com/company/travelmate-aps',
      companyOverview: 'Corporate travel booking and expense management platform.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'CyberGuard s.r.o.',
      contactName: 'Tomas Novak',
      contactTitle: 'VP Sales',
      phoneNumber: '+420601234567',
      country: 'CZ',
      location: 'Prague',
      headcount: 85,
      industry: 'Cybersecurity',
      email: 'tomas.novak@cyberguard.cz',
      website: 'https://cyberguard.cz',
      personalLinkedin: 'https://linkedin.com/in/tomasnovak',
      companyLinkedin: 'https://linkedin.com/company/cyberguard-cz',
      companyOverview: 'Managed SOC services for Central European enterprises.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'AutoParts SRL',
      contactName: 'Ion Popescu',
      contactTitle: 'Director of Partnerships',
      phoneNumber: '+40721234567',
      country: 'RO',
      location: 'Bucharest',
      headcount: 220,
      industry: 'Automotive',
      email: 'ion.popescu@autoparts.ro',
      website: 'https://autoparts.ro',
      personalLinkedin: 'https://linkedin.com/in/ionpopescu',
      companyLinkedin: 'https://linkedin.com/company/autoparts-srl',
      companyOverview: 'EV charging infrastructure and fleet electrification consulting.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'InsurFlow Kft.',
      contactName: 'Gabor Nagy',
      contactTitle: 'CEO',
      phoneNumber: '+36201234567',
      country: 'HU',
      location: 'Budapest',
      headcount: 40,
      industry: 'InsurTech',
      email: 'gabor.nagy@insurflow.hu',
      website: 'https://insurflow.hu',
      personalLinkedin: 'https://linkedin.com/in/gabornagy',
      companyLinkedin: 'https://linkedin.com/company/insurflow-kft',
      companyOverview: 'Digital insurance distribution platform for brokers.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'LearnHub GmbH',
      contactName: 'Julia Fischer',
      contactTitle: 'Head of Growth',
      phoneNumber: '+4916012345678',
      country: 'DE',
      location: 'Hamburg',
      headcount: 55,
      industry: 'EdTech',
      email: 'julia.fischer@learnhub.de',
      website: 'https://learnhub.de',
      personalLinkedin: 'https://linkedin.com/in/juliafischer',
      companyLinkedin: 'https://linkedin.com/company/learnhub-gmbh',
      companyOverview: 'Corporate upskilling platform with AI-generated learning paths.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'AgriSense Ltd',
      contactName: 'David Wilson',
      contactTitle: 'CTO',
      phoneNumber: '+447912345678',
      country: 'GB',
      location: 'Edinburgh',
      headcount: 35,
      industry: 'AgTech',
      email: 'david.wilson@agrisense.co.uk',
      website: 'https://agrisense.co.uk',
      personalLinkedin: 'https://linkedin.com/in/davidwilson',
      companyLinkedin: 'https://linkedin.com/company/agrisense-ltd',
      companyOverview: 'IoT sensor network for precision agriculture and crop monitoring.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'ShipFast BV',
      contactName: 'Pieter Bakker',
      contactTitle: 'COO',
      phoneNumber: '+31630123456',
      country: 'NL',
      location: 'Utrecht',
      headcount: 100,
      industry: 'Logistics',
      email: 'pieter.bakker@shipfast.nl',
      website: 'https://shipfast.nl',
      personalLinkedin: 'https://linkedin.com/in/pieterbakker',
      companyLinkedin: 'https://linkedin.com/company/shipfast-bv',
      companyOverview: 'Same-day delivery marketplace connecting local couriers to e-commerce.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'QuantumBit SA',
      contactName: 'Antoine Moreau',
      contactTitle: 'VP Research',
      phoneNumber: '+33682345678',
      country: 'FR',
      location: 'Grenoble',
      headcount: 20,
      industry: 'Quantum Computing',
      email: 'antoine.moreau@quantumbit.fr',
      website: 'https://quantumbit.fr',
      personalLinkedin: 'https://linkedin.com/in/antoinemoreau',
      companyLinkedin: 'https://linkedin.com/company/quantumbit-sa',
      companyOverview: 'Quantum simulation software for pharmaceutical drug discovery.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'WealthPilot AG',
      contactName: 'Christina Meier',
      contactTitle: 'Head of Sales',
      phoneNumber: '+41781234567',
      country: 'CH',
      location: 'Geneva',
      headcount: 50,
      industry: 'WealthTech',
      email: 'christina.meier@wealthpilot.ch',
      website: 'https://wealthpilot.ch',
      personalLinkedin: 'https://linkedin.com/in/christinameier',
      companyLinkedin: 'https://linkedin.com/company/wealthpilot-ag',
      companyOverview: 'Robo-advisory and portfolio management for Swiss private banks.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'VoiceAI GmbH',
      contactName: 'Martin Kraus',
      contactTitle: 'Founder',
      phoneNumber: '+4917698765432',
      country: 'DE',
      location: 'Cologne',
      headcount: 15,
      industry: 'Artificial Intelligence',
      email: 'martin.kraus@voiceai.de',
      website: 'https://voiceai.de',
      personalLinkedin: 'https://linkedin.com/in/martinkraus',
      companyLinkedin: 'https://linkedin.com/company/voiceai-gmbh',
      companyOverview: 'Conversational AI agents for customer service automation.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'LegalSync Ltd',
      contactName: 'Sarah Thompson',
      contactTitle: 'VP Product',
      phoneNumber: '+447801234567',
      country: 'GB',
      location: 'Bristol',
      headcount: 40,
      industry: 'LegalTech',
      email: 'sarah.thompson@legalsync.co.uk',
      website: 'https://legalsync.co.uk',
      personalLinkedin: 'https://linkedin.com/in/sarahthompson',
      companyLinkedin: 'https://linkedin.com/company/legalsync-ltd',
      companyOverview: 'Contract lifecycle management and e-signature for law firms.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'EventGrid AB',
      contactName: 'Katarina Svensson',
      contactTitle: 'CEO',
      phoneNumber: '+46731234567',
      country: 'SE',
      location: 'Gothenburg',
      headcount: 30,
      industry: 'Events',
      email: 'katarina.svensson@eventgrid.se',
      website: 'https://eventgrid.se',
      personalLinkedin: 'https://linkedin.com/in/katarinasvensson',
      companyLinkedin: 'https://linkedin.com/company/eventgrid-ab',
      companyOverview: 'Virtual and hybrid event management for B2B conferences.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'CleanWater Lda',
      contactName: 'Miguel Santos',
      contactTitle: 'Director of Sales',
      phoneNumber: '+351921234567',
      country: 'PT',
      location: 'Lisbon',
      headcount: 75,
      industry: 'CleanTech',
      email: 'miguel.santos@cleanwater.pt',
      website: 'https://cleanwater.pt',
      personalLinkedin: 'https://linkedin.com/in/miguelsantos',
      companyLinkedin: 'https://linkedin.com/company/cleanwater-lda',
      companyOverview: 'Industrial water treatment and recycling solutions.',
      ownerId: bdr2.id,
    },
    {
      companyName: 'SmartParking SpA',
      contactName: 'Luca Bianchi',
      contactTitle: 'Head of Partnerships',
      phoneNumber: '+393401234567',
      country: 'IT',
      location: 'Rome',
      headcount: 60,
      industry: 'Smart Cities',
      email: 'luca.bianchi@smartparking.it',
      website: 'https://smartparking.it',
      personalLinkedin: 'https://linkedin.com/in/lucabianchi',
      companyLinkedin: 'https://linkedin.com/company/smartparking-spa',
      companyOverview: 'IoT-based parking management for municipalities and airports.',
      ownerId: bdr1.id,
    },
    {
      companyName: 'DataVault Ltd',
      contactName: "Rachel O'Connor",
      contactTitle: 'Head of Engineering',
      phoneNumber: '+353871234567',
      country: 'IE',
      location: 'Dublin',
      headcount: 45,
      industry: 'Data Security',
      email: 'rachel.oconnor@datavault.ie',
      website: 'https://datavault.ie',
      personalLinkedin: 'https://linkedin.com/in/racheloconnor',
      companyLinkedin: 'https://linkedin.com/company/datavault-ie',
      companyOverview: 'GDPR-compliant data anonymization and encryption services.',
      ownerId: bdr2.id,
    },
  ];

  for (const lead of testLeads) {
    const existing = await prisma.lead.findFirst({
      where: { phoneNumber: lead.phoneNumber },
    });

    if (!existing) {
      const created = await prisma.lead.create({ data: lead });
      console.log(`  ✅ Lead: ${created.companyName} (${created.contactName})`);
    } else {
      console.log(`  ⏭️  Lead already exists: ${lead.companyName}`);
    }
  }

  console.log('\n🎉 Seed completed!');
  console.log('\n📋 Test credentials:');
  console.log('   Admin: admin@signalhunt.com / admin123456');
  console.log('   BDR 1: bdr1@signalhunt.com / bdr123456');
  console.log('   BDR 2: bdr2@signalhunt.com / bdr123456');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
